#storage:
#  image: alpine:latest
#  command:
#    - /bin/true
#  volumes:
#   - ./storage/mysql:/var/lib/mysql
#   - ./storage/redis:/data
mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: yy_water_station
    MYSQL_USER: greaspace
    MYSQL_PASSWORD: greaspace_1024
  volumes:
    - ./storage/mysql:/var/lib/mysql
  ports:
    - 3306:3306
redis:
  image: redis:alpine
  volumes:
    - ./storage/redis:/data
  ports:
    - 6379:6379
